name: jajankeun_app
description: A new Flutter project.
publish_to: 'none' # private project

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    # Tambahkan aset lainnya di bawah sini
    # - assets/images/
    # - assets/icons/

  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700
